### PR TITLE
Testing homu usage via usage test

### PR DESCRIPTION
**Pull request by cgwalters**

### CODE REVIEW

**Comment by cgwalters** [comment]
:warning: Do not click the "Merge pull request" button here; see http://escher.verbum.org:54856/ for Homu usage instructions  :warning:

**Comment by alexlarsson** [comment]
r+

**Comment by alexlarsson** [comment]
Wasn't that supposed to merge it?

**Comment by cgwalters** [comment]
You need to prefix with "@cgwalters-bot"

**Comment by alexlarsson** [comment]
@cgwalters-bot r+ f609bfe

**Comment by cgwalters** [comment]
@cgwalters-bot retry

**Comment by alexlarsson** [comment]
@cgwalters-bot r+ 6cce688

**Comment by alexlarsson** [comment]
@cgwalters-bot r+

**Pull request merged**
